apiVersion: apps/v1
kind: Deployment
metadata:
  name: cairiq-companion-prod
  namespace: cairiq-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cairiq-companion-prod
  template:
    metadata:
      labels:
        app: cairiq-companion-prod
    spec:
      imagePullSecrets:
        - name: devjasminesaasaks60cb-auth
      containers:
        - name: cairiq-companion-prod
          image: REPLACE_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ENV
              value: "prod"
            - name: VITE_API_BASE_URL
              value: "https://api.cairiqhealth.ai"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
